# fly.toml app configuration file generated for my-frontend on 2025-03-15T00:27:45+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-frontend'
primary_region = 'sin'

[build]

[env]
  VITE_BACKEND_URL= "https://my-backend-bold-butterfly-6572.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
