# fly.toml app configuration file generated for my-mongodb on 2025-03-14T23:58:29+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-mongodb'
primary_region = 'sin'

[build]
  image = 'mongo:6.0'

[mounts]
  source = "mongo_data"
  destination = "/data/db"

[http_service]
  internal_port = 27017
  protocol = "tcp"
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
